spring:
  data:
    mongodb:
      # En producción tomará la URL de la variable de entorno MONGO_URI
      uri: ${MONGO_URI}

  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GCP_PROJECT_ID:project-da37a9fc-9c9e-4d37-822}
          location: us-central1
          chat:
              options:
                model: gemini-2.5-flash
                temperature: 0.1

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    com.workflow: INFO
  project-id: empresa-22cd0

app:
  uploads:
    dir: /tmp/uploads
  firebase:
    project-id: empresa-22cd0 # Este ID es el que el SDK usará para enviar los mensajes
    # credentials-path: # ELIMINA O DEJA VACÍO ESTO. Google lo detectará automáticamente.
