spring:
  data:
    mongodb:
      # En producción tomará la URL de la variable de entorno MONGO_URI
      uri: ${MONGO_URI}

  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GOOGLE_CLOUD_PROJECT_ID}
          location: ${GOOGLE_CLOUD_LOCATION:global}
          # En producción la autenticación se hace usualmente usando ADC (Application Default Credentials)
          # Si usas una cuenta de servicio, la variable de entorno GOOGLE_APPLICATION_CREDENTIALS debe apuntar al .json
          chat:
            options:
              model: ${VERTEX_MODEL:gemini-2.0-flash-001}
              temperature: 0.1

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    com.workflow: INFO
